[build]
  command = "npm run scully:build"
  functions = "./functions"
  publish = "dist/static/"
[dev]
  command = "npm run start"
  functions = "./functions"
  publish = "src"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
