[build]
  command = "npm run scully:build"
  functions = ""
  publish = "dist/static/"
[dev]
  command = "npm run start"
  functions = ""
  publish = "src"
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    record = true
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
